stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

# Étape de construction de l'image Docker
build:
  stage: build
  script:
    - docker build -t my-app:${CI_COMMIT_REF_NAME} .

# Déploiement sur l'environnement de développement
deploy_dev:
  stage: deploy
  only:
    - develop
  script:
    - docker-compose -f docker-compose.dev.yml up -d

# Déploiement sur l'environnement de production
deploy_prod:
  stage: deploy
  only:
    - main
  script:
    - docker-compose -f docker-compose.prod.yml up -d
