version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80" # Port différent pour éviter les conflits
    volumes:
      - .:/var/www/html
    environment:
      - ENVIRONMENT=development
